substitutions:
  status_three_way_valve: 3-vägs Ventil
  status_three_way_valve_2: 3-vägs Ventil 2
  heatpump_climate_dhw: Tappvarmvatten Klimat
  dhw_temp: Tappvarmvatten Temp
  dhw_secondary_temp: Tappvarmvatten sekundär Temp
  status_dhw_forced: Tappvarmvatten Tvinga
  dhw_flow_temp_drop: Tappvarmvatten Max Temperaturfall
  status_prohibit_dhw: Tappvarmvatten Förbjud
  dhw_flow_temp_target: Tappvarmvatten Börvärde
  status_dhw_eco: Tappvarmvatten Eco
  esp_ip: ESP IP
  internal_esp_temperature: ESP Intern Temp
  esp_sidd: ESP SSID
  uptime: ESP Uptime
  esp_version: ESP Version
  restart_button: ESP Restart
  status_in1_request: In1 Termostat
  status_in6_request: In6 Termostat 2
  status_in5_request: In5 Ute Termostat
  heatpump_select_dhw_mode: Tappvarmvatten Läge
  normal: Normal
  eco: Eco
  version: ESP Version
  led_brightness: LED Ljusstyrka
  led_switch: LED
  heatpump_switch_force_dhw: Tvinga Tappvarmvatten
  heatpump_switch_power_mode: Värmepump
  heatpump_switch_holiday: Semesterläge
  wifi_signal_proc: WiFi Signal %
  wifi_signal_db: WiFi Signal dB
  z1_flow_temp_target: Zon1 V/K Börvärde
  status_prohibit_cool_z1: Zon1 Förbjud Kyla
  status_prohibit_heating_z1: Zon1 Förbjud Värme
  heatpump_climate_z1: Zon1 Klimat
  z1_room_temp_target: Zon1 Rumsbörvärde
  z1_room_temp: Zon1 Rumstemperatur
  heatpump_number_z2_set_flow_temperature: Zon2 V/K Börvärde
  z2_flow_temp_target: Zon2 V/K Börvärde
  status_prohibit_cool_z2: Zon2 Förbjud Kyla
  status_prohibit_heating_z2: Zon2 Förbjud Värme
  heatpump_number_z2_set_room_temperature: Zon2 Rrumsbörvärde
  heatpump_climate_z2: Zon2 Klimat
  z2_room_temp_target: Zon2 Rumsbörvärde
  z2_room_temp: Zon2 Rumstemperatur
  boiler_flow_temp: Tilloppstemp Panna
  boiler_return_temp: Returtemp Panna
  status_booster: Tillskott Värme
  compressor_frequency: Kompressorfrekvens
  controller_version_text: Controllerversion
  cool_consumed: Kyla Förbrukad
  cool_cop: Kyla COP
  cool_delivered: Kyla Levererad
  status_defrost: Avfrostning
  dhw_consumed: Tappvarmvatten Förbrukad
  dhw_cop: Tappvarmvatten COP
  dhw_delivered: Tappvarmvatten Levererad
  hp_feed_temp: Matning Temp
  z1_feed_temp: Z1 Matning Temp
  z2_feed_temp: Z2 Matning Temp
  flow_rate: Flödeshastighet
  heat_source_text: Värmekälla
  heatpump: Värmepump
  immersion_heater: Elpatron
  booster_heater: Tillskott
  immersion_and_booster_heater: Elpatron Och Tillskott
  boiler: Panna
  heating_consumed: Värme Förbrukad
  heating_cop: Värme COP
  heating_delivered: Värme Levererad
  status_holiday: Semesterläge
  status_immersion: Elpatron
  legionella_prevention_temp: Legionella Börvärde
  heatpump_select_operating_mode: Valt driftläge
  heat_target_temperature: Värme Börfärde
  heat_flow_temperature: Tilloppstemperatur Värme
  heat_compensation_curve: Värmekompensationskurva
  cool_target_temperature: Kyla Börvärde
  cool_flow_temperature: Kyla Tilloppstemperatur
  operation_off: "Off"
  hotwater: Värmer Vatten
  heating: Rumsuppvärmning
  cooling: Rumskylning
  frost_protection: Frostskydd
  legionella_prevention: Legionella Motverkan
  runtime: Drifttid
  status_operation: Driftläge
  output_power: Effektuttag
  computed_output_power: Beräknat Effektuttag
  outside_temp: Utetemp
  hp_refrigerant_temp: Köldmedium Temp
  hp_refrigerant_condensing_temp: Köldmedium Kondenseringstemp
  hp_return_temp: Retur Temp
  z1_return_temp: Z1 Retur Temp
  z2_return_temp: Z2 Retur Temp 
  status_water_pump: Cirkulationspump Status
  status_water_pump_2: Cirkulationspump 2 Status
